spring.application.name=user-service
server.port=8081

# Usa le variabili se presenti, altrimenti usa i valori di default del .env
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT_EXTERNAL:5433}/${DB_NAME:gatewaytempl}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true