services:
  postgres:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - micro-network

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${DB_PORT_INTERNAL}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - micro-network

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
    depends_on:
      - user-service
    networks:
      - micro-network

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge

volumes:
  postgres_data: