server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  # Questa sezione deve essere allineata correttamente sotto 'spring'
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      
      routes:
        - id: user-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /users/**